@startuml

actor "Wi-Fi cliens" as wifi
cloud "414-000" as number
cloud MTS
cloud Yarnet

rectangle "Вход" {
  component "Zyxel Keenetic" as Zyxel
  [Zyxel]
  [Zyxel 2]
  [linksys]
}

node "Asterisk\n\n\n\n\n\n" as Asterisk {

}

node phones [
  **Телефоны**
  ====
  phone1
  ----
  phone2
  ----
  phone3
  ----
  ...
]

node "\n\nICS\n\n\n\n" as ICS {
  
}

node VM2 { 
  rectangle r2 [
    clients1
    ----
    clients2
    ----
    clients3
    ----
    clients4
    ----
    test
    ----
    intranet
  ]
}

node "**Clients5**\n\n\n\n\n\n\n\n\n" as Clients5 {
  
}

node Master {
rectangle r1 [
  Windows 7 Future2
  ----
  Windows 7 SC
  ----
  Windows 7 Принтер
  ----
  Windows Server 2008 R2 1С
  ----
  *.direct
  ----
  portal
  ----
  mail.clients
  ----
  aseo
]
}

node comps [
  **Рабочие станции**
  ===
  comp1
  ----
  comp2
  ----
  comp3
  ----
  comp4
  ----
  ...
]

frame "Принтеры" {
  [HP]
  [Kyocera]
  [Samsung]
}

(MTS) -d-> [Zyxel]
(Yarnet) -d-> [Zyxel]
[Zyxel] --> [Zyxel 2]
[Zyxel] --> Asterisk

[Zyxel 2] -l-> wifi

[Zyxel] --> ICS
ICS -d-> [Коммутаторы]

number --> [linksys]
[linksys] -> [Zyxel]
Asterisk -r-> phones

[Коммутаторы] -> VM2
[Коммутаторы] -> Master
[Коммутаторы] -d-> Clients5
[Коммутаторы] --> [HP]
[Коммутаторы] --> [Kyocera]
[Коммутаторы] --> [Samsung]
[Коммутаторы] --> comps


note bottom of VM2
  192.168.0.247
  Windows Hyper-V 2008 R2
end note

note bottom of Master
  192.168.0.252
  Windows Server 2008 R2
end note

note right of ICS
  Интернет Контроль Сервер
  192.168.255.254
  192.168.1.254
end note

note bottom of Asterisk
192.168.1.253
end note

@enduml